# Mean-Variance-Standard Deviation Calculator

This notebook documents my problem-solving process of the project. My first action is to make sure I understand the instructions. I made sure to understand the required inputs and the desired output. For instance, it was not clear in the instruction whether the formula is for sample or population. I checked the `test_module.py`, and the expected results indicates the formula is for population. Next, I outlined the steps I needed to make. The first of which is refreshing on the formulas required. I then took note of the functions I would need before starting. Next, I started discovery writing the codes first to give me an outline of the sub-goals or processes that needed to happen to reach the final desired output. Afterwards, I tested the code. There were two major errors. One is calculating the variance for *axis1*, which initially used the same formula for *axis0*. I reshaped the array and change the direction of summation to solve this issue. The last error I had to fix was the mismatch in decimal numbers. I realized that I needed to use the `numpy.sum()` function instead of the `sum()` function. The key to diagnosing these errors is by checking the error messages, comparing the actual and expected results, and by doing a line editing. This is inspired from the line editing in book editing. The Jupyter notebook is instrumental in making this process is easy. I run the code line by line until I found where the error starts. For next time, if I ever had to come back to this code, I want to see how I could optimize the code to run with fewer lines.

In [241]:
# Import requisite library
import numpy as np

In [242]:
# I used one of the arrays from the tests
list = [2,6,2,8,4,0,1,5,7]

In [243]:
# I take note of the list length for later use as the "n" in the formula
total = len(list)
total

9

The if statement, inequality, and boolean operators is something I learned already. However, I did not know the codes for displaying errors, so I looked it up online. I place it here only in markdown, since I cannot run it here.

`if total <9 | total >9:`

        `raise ValueError("List must contain nine numbers.")`

In [244]:
# Convert list to array
a = np.array(list)
type(a)

numpy.ndarray

In [245]:
# Reshape the array into a 3 by 3 matrix
a = np.reshape(a, (3,3)) #reshape into 3by3 matrix
a

array([[2, 6, 2],
       [8, 4, 0],
       [1, 5, 7]])

In [246]:
# Record dimensions to later extract it for the "n" value
# This is not completely necessary, but I wanted it to be easily modifiable to accept more numbers
shape = np.array(a.shape)
shape

array([3, 3])

In [247]:
# Counted the rows and stored for later use
axis_0 = shape[0]
axis_0

3

In [248]:
# Counted the rows and stored for later use
axis_1 = shape[1]
axis_1

3

In [249]:
# Sum for each column
axis0_sum = np.sum(a, axis=0)
axis0_sum # I made sure to verify the results in each step

array([11, 15,  9])

In [250]:
# Sum for each row
axis1_sum = np.sum(a, axis=1)
axis1_sum

array([10, 12, 13])

In [251]:
# Sum for the list
list_sum = np.sum(list)
list_sum

35

In [252]:
# Mean for columns
axis0_mean = axis0_sum/axis_0
axis0_mean

array([3.66666667, 5.        , 3.        ])

In [253]:
# Mean for rows
axis1_mean = axis1_sum/axis_1
axis1_mean

array([3.33333333, 4.        , 4.33333333])

In [254]:
# Mean for the list
list_mean = list_sum/total
list_mean

3.888888888888889

In [255]:
# Population variance for the columns
axis0_var = np.sum(((a - axis0_mean)**2), axis=0)/axis_0
axis0_var

array([9.55555556, 0.66666667, 8.66666667])

In [256]:
# I tested the codes here before applying to the final code. 
# I started from the inside then start building it out. 
# I first reshaped it so it was subtracted the right way
# I then have to add the axis argument to make sure the differences are added correctly
np.sum(((a - np.reshape(axis1_mean, (3,1)))**2), axis=1) 

array([10.66666667, 32.        , 18.66666667])

In [257]:
# Population variance for the rows
axis1_var = np.sum(((a - np.reshape(axis1_mean, (3,1)))**2), axis=1)/axis_1 #This is where one of the major error occured.
axis1_var

array([ 3.55555556, 10.66666667,  6.22222222])

In [258]:
# Population variance for the list
list_var = (np.sum((list - list_mean)**2))/total #This is where the second major error occured.
list_var

6.987654320987654

In [259]:
# Standard deviation for the columns
axis0_std = axis0_var**0.5

In [260]:
# Standard deviation for the rows
axis1_std = axis1_var**0.5
axis1_std

array([1.88561808, 3.26598632, 2.49443826])

In [261]:
# Standard deviation for the list
list_std = list_var**0.5 #This is where the second major error is reflected. 
list_std

2.6434171674156266

In [262]:
# I checked this first, but it turns out that I had to use np.sum instead of sum in the formula for variance.
np.sqrt(list_var)

2.6434171674156266

In [263]:
# Extracting the max for the columns
axis0_max = np.max(a, axis=0)
axis0_max

array([8, 6, 7])

In [264]:
# Extracting the max for the rows
axis1_max = np.max(a, axis=1)
axis1_max

array([6, 8, 7])

In [265]:
# Extracting the max for the list
list_max = np.max(list)
list_max

8

In [266]:
# Extracting the min for the columns
axis0_min = np.min(a, axis=0)
axis0_min

array([1, 4, 0])

In [267]:
# Extracting the max for the rows
axis1_min = np.min(a, axis=1)
axis1_min

array([2, 0, 1])

In [268]:
# Extracting the max for the list
list_min = np.min(list)
list_min

0

In [269]:
# Compiling the mean to a list
# I also made a mistake here and had to switch it from an array to a list
mean_list = [axis0_mean.tolist(), axis1_mean.tolist(), list_mean.tolist()]
mean_list

[[3.6666666666666665, 5.0, 3.0],
 [3.3333333333333335, 4.0, 4.333333333333333],
 3.888888888888889]

In [270]:
# Compiling the variance to a list
var_list = [axis0_var.tolist(), axis1_var.tolist(), list_var.tolist()]
var_list

[[9.555555555555557, 0.6666666666666666, 8.666666666666666],
 [3.555555555555556, 10.666666666666666, 6.222222222222221],
 6.987654320987654]

In [271]:
# Compiling the standard deviation to a list
std_list = [axis0_std.tolist(), axis1_std.tolist(), list_std.tolist()]
std_list

[[3.091206165165235, 0.816496580927726, 2.943920288775949],
 [1.8856180831641267, 3.265986323710904, 2.494438257849294],
 2.6434171674156266]

In [272]:
# Compiling the max to a list
max_list = [axis0_max.tolist(), axis1_max.tolist(), list_max.tolist()]
max_list

[[8, 6, 7], [6, 8, 7], 8]

In [273]:
# Compiling the min to a list
min_list = [axis0_min.tolist(), axis1_min.tolist(), list_min.tolist()]
min_list

[[1, 4, 0], [2, 0, 1], 0]

In [274]:
# Compiling the sum to a list
sum_list = [axis0_sum.tolist(), axis1_sum.tolist(), list_sum.tolist()]
sum_list

[[11, 15, 9], [10, 12, 13], 35]

In [275]:
# Compiling the lists to the dictionary
calculations = {}
calculations['mean'] = mean_list
calculations['variance'] = var_list
calculations['standard deviation'] = std_list
calculations['max'] = max_list
calculations['min'] = min_list
calculations['sum'] = sum_list
calculations

{'mean': [[3.6666666666666665, 5.0, 3.0],
  [3.3333333333333335, 4.0, 4.333333333333333],
  3.888888888888889],
 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666],
  [3.555555555555556, 10.666666666666666, 6.222222222222221],
  6.987654320987654],
 'standard deviation': [[3.091206165165235,
   0.816496580927726,
   2.943920288775949],
  [1.8856180831641267, 3.265986323710904, 2.494438257849294],
  2.6434171674156266],
 'max': [[8, 6, 7], [6, 8, 7], 8],
 'min': [[1, 4, 0], [2, 0, 1], 0],
 'sum': [[11, 15, 9], [10, 12, 13], 35]}